from django import forms
from django.conf import settings
from django.core.mail import EmailMessage


class Mail(forms.Form):
    email = forms.CharField(max_length=300, label='Email')
    subject = forms.CharField(max_length=100, label='Subject')
    message = forms.CharField(max_length=1000, label='Message')

    def send(self):
        message = """This mail was generated by the contactform on scienceshaped.com
The users email adress: """ + self.cleaned_data['email'] + """

""" + self.cleaned_data['message']

        EmailMessage(
            subject=self.cleaned_data['subject'],
            body=message,
            from_email=self.cleaned_data['email'],
            to=settings.CONTACT_EMAIL,
            reply_to=[self.cleaned_data['email']],
            headers={'From': 'ScienceShaped Contactform'}
        ).send()
