from django.shortcuts import render
from projects.models import Illustration, Testimonial
from projects.forms import IllustrationFilter
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import EmailMessage
from .forms import Mail
from django.conf import settings

def index(request):
    illustrations = Illustration.objects.order_by('-date')
    testimonials = Testimonial.objects.order_by('-pub_date')
    if request.method == 'POST':
        form = IllustrationFilter(request.POST)
        if form.is_valid():
            search = str(form.cleaned_data['search']).lower()
            if search != "all":
                illustrations = []
                for illustration in Illustration.objects.order_by('-date'):
                    if search in illustration.tags.lower():
                        illustrations.append(illustration)
        else:
            form = Mail(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                subject = form.cleaned_data['subject']
                message = 'This mail was generated by the contactform on scienceshaped.com\n'
                message += 'The users email adress: ' + email + '\n\n'
                message += form.cleaned_data['message']
                EmailMessage(subject, message, email, [settings.CONTACT_EMAIL], reply_to=[email], headers={'From': 'ScienceShaped Contactform'}).send()

    filterForm = IllustrationFilter()
    mailForm = Mail()
    context = {
        'illustrations': illustrations,
        'testimonials': testimonials,
        'filterForm': filterForm,
        'mailForm': mailForm,
    }

    return render(request, 'index.html', context)

def login(request):
    return HttpResponseRedirect('/authentication/login')
