from django.shortcuts import render
from projects.models import Illustration, Testimonial
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import EmailMessage
from .forms import Mail
from django.conf import settings
import projects.views

def index(request, tag='all'):
    testimonials = Testimonial.objects.order_by('-pub_date')
    if tag == 'all':
        illustrations = Illustration.objects.order_by('-date')
    else:
        illustrations = []
        for illustration in Illustration.objects.order_by('-date'):
            if tag in illustration.tags.lower():
                illustrations.append(illustration)
    tags = projects.views.getIllustrationTags()
    if request.method == 'POST':
        mailForm = Mail(request.POST)
        if mailForm.is_valid():
            email = mailForm.cleaned_data['email']
            subject = mailForm.cleaned_data['subject']
            message = 'This mail was generated by the contactform on scienceshaped.com\n'
            message += 'The users email adress: ' + email + '\n\n'
            message += mailForm.cleaned_data['message']
            EmailMessage(subject, message, email, [settings.CONTACT_EMAIL], reply_to=[email], headers={'From': 'ScienceShaped Contactform'}).send()
    else:
        mailForm = Mail(initial={
            'email': '',
            'subject': '',
            'message': ''
        })

    context = {
        'illustrations': illustrations,
        'testimonials': testimonials,
        'mailForm': mailForm,
        'tags': tags,
    }
    return render(request, 'index.html', context)

def login(request):
    return HttpResponseRedirect('/authentication/login')
